# -*- coding: utf-8 -*-
"""kmeans_segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GVFMeD0ZnuybYMbr3lXIHwMdhjg0TLf
"""

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt


data = pd.DataFrame({
    'Age': [25, 45, 35, 50, 23, 40, 60, 48],
    'Income': [30, 80, 50, 90, 25, 60, 100, 85]
})

kmeans = KMeans(n_clusters=2, random_state=42)
labels = kmeans.fit_predict(data)


inertia = kmeans.inertia_
sil_score = silhouette_score(data, labels)

print("Inertia:", inertia)
print("Silhouette Score:", sil_score)


plt.scatter(data['Age'], data['Income'], c=labels)
plt.xlabel("Age")
plt.ylabel("Income")
plt.title("Customer Segmentation")
plt.show()